### ISSUE TITLE
1.19.2 support

### ISSUE THREAD

**Issue by DanMeadWasTaken** [uku3lig/healthindicator#1]
This is one of those mods I didn't realize I needed/wanted till i saw it. Only problem is, atleast on the modrinth version as i can't find a curseforge version, when i tried to run it, It says it needs 1.19 while I'm running 1.19.2

**Comment by uku3lig** [comment]
Done, download [here](https://modrinth.com/mod/healthindicator/version/1.0.1%2Bmc1.19.2).

Also, there is no such thing as a CurseForge version, as it is an absolute pain to work with.

**Comment by DanMeadWasTaken** [comment]
Tysm
