### ISSUE TITLE
lang file issues

### ISSUE THREAD

**Issue by JuceInUse** [uku3lig/healthindicator#2]
In the lang file, your play sound translation key is "healthindicator.playsound", but the keys are case sensitive; It should be "healthindicator.playSound". Small issue, but it makes the modmenu config look wonky

**With Issue:**
![image](https://user-images.githubusercontent.com/85078618/198885607-b699c87f-c11c-4b60-a84d-a803d49e76ea.png)

**Expected Behavior:**
![image](https://user-images.githubusercontent.com/85078618/198885746-db0fb8b9-7228-4d40-ab4d-87540ddf9e45.png)

**Patched Lang File:**
`{`
`  "healthindicator.health": "Health Points",`
`  "healthindicator.health.tooltip": "Minimum health points to show the warning. 2 points = 1 heart",`
`  "healthindicator.playSound": "Play Sound",`
`  "healthindicator.position": "Position"`
`}`

**Comment by uku3lig** [comment]
fixed in latest commit
